POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "rihc",
  "password": "richard_67",
  "name": "Adam Richard",
  "gender": "male"
}
###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "JoeBiden",
    "password": "biden@123"
}
###

GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzg5MDI4fQ.NXMU909sJR_XRIDKkE1I30ilbyINWqqtoBu8BfGwmLE
###


GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzg5MDI4fQ.NXMU909sJR_XRIDKkE1I30ilbyINWqqtoBu8BfGwmLE
###

GET http://localhost:3000/user/follower/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzg5MDI4fQ.NXMU909sJR_XRIDKkE1I30ilbyINWqqtoBu8BfGwmLE
###


GET http://localhost:3000/tweets/:tweetId/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzg5MDI4fQ.NXMU909sJR_XRIDKkE1I30ilbyINWqqtoBu8BfGwmLE
###


GET http://localhost:3000/tweets/:tweetId/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzg5MDI4fQ.NXMU909sJR_XRIDKkE1I30ilbyINWqqtoBu8BfGwmLE
###

GET http://localhost:3000/tweets/:tweetId/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzg5MDI4fQ.NXMU909sJR_XRIDKkE1I30ilbyINWqqtoBu8BfGwmLE
###



GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzg5MDI4fQ.NXMU909sJR_XRIDKkE1I30ilbyINWqqtoBu8BfGwmLE
###


POST http://localhost:3000/user/tweets/
Content-Type: application/json

{
    "tweet": "The Mornings are Buetifull"
}
###


DELETE http://localhost:3000/tweets/:tweetId/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzg5MDI4fQ.NXMU909sJR_XRIDKkE1I30ilbyINWqqtoBu8BfGwmLE
###
